trigger:
- master

jobs:
- job: Build
  timeoutInMinutes: 180
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - bash: scripts/docker_build.sh
  - task: CopyFiles@2
    inputs:
      contents: 'xe303c12.zip'
      targetFolder: $(Build.ArtifactStagingDirectory)
  - task: GitHubRelease@0
    inputs:
      gitHubConnection: 'github'
      repositoryName: '13pgeiser/debian_chromebook_XE303C12'
      action: 'create'
      assets: $(Build.ArtifactStagingDirectory)/*.zip
