trigger:
- master

jobs:
- job: Build
  timeoutInMinutes: 180
  pool:
    vmImage: 'Ubuntu-18.04'
  steps:
  - bash: make check
  - bash: scripts/docker_build.sh
  - task: CopyFiles@2
    inputs:
      Contents: |
        release/**
      targetFolder: $(Build.ArtifactStagingDirectory)
  - task: GitHubRelease@0
    inputs:
      gitHubConnection: '13pgeiser_azure'
      repositoryName: '13pgeiser/debian_chromebook_XE303C12'
      action: 'create'
      assets: |
        $(Build.ArtifactStagingDirectory)/release/**

