name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check
      run: make check
    - name: Build
      run: make run
    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "release/*"
        token: ${{ secrets.GITHUB_TOKEN }}

